Autoscale the affine transform when viewer and overlay images have different pixel sizes.
qupath/qupath-extension-align pull request #10
Opened 2024-08-20 10:49 UTC by zindy

Hello,

this pull request is for calculating a scaling factor between viewer and overlay images if their pixel size is different, and apply it to the transform matrix.

This issue (aligning images with different pixel sizes) was discussed on the forum:
https://forum.image.sc/t/align-tool-difference-in-pixel-size-for-the-fixed-and-moving-images-is-not-accounted-for/95973

Scaling can occur when a new overlay is selected and when the reset button is pressed. The new code handles both scenarios.

Cheers,
Egor

2025-04-10 08:49 UTC, petebankhead requested changes
I agree that automatically fixing the scales would be really useful and important. I haven't tried running it yet, but have added some comments from reading the code - please let me know if you'd like to update your PRs, otherwise one of us will look into reviving this extension soon and can use them instead for inspiration.

2025-04-10 08:49 UTC, petebankhead commented on src/main/java/qupath/ext/align/gui/ImageAlignmentPane.java
> +			overlay.resetAffine();
Is the null check not needed, i.e. is there absolutely no way for `getSelectedOverlay()` to return null?

2025-04-10 08:49 UTC, petebankhead commented on src/main/java/qupath/ext/align/gui/ImageServerOverlay.java
> +        // Calculate the a and y scaling factor
I haven't tried it, but this looks like it wouldn't handle the case where the pixel size information is missing for at least one image.

Technically, the pixel width and height *might* not be in µm - you can use e.g. `PixelCalibration.getPixelWidthUnit()` to check that the values match for the two calibration objects, and then use `PixelCalibration.getPixelWidth()` to calculate the ratios *only* if they do.

2025-04-10 08:49 UTC, petebankhead commented on src/main/java/qupath/ext/align/gui/ImageServerOverlay.java
> +	private PixelCalibration viewerCalibration;
I'm not certain about the naming here - `viewerCalibrattion` sounds to me that it relates to the magnification in the viewer, not the image currently open within the viewer.

Not sure what the names should be, but maybe `currentServerCalibration` and `overlayServerCalibration`?

Or perhaps `viewerCalibration` and `overlayCalibration` would be fine... just not `serverCalibration` since it's not clear *which* server.

2025-04-12 07:39 UTC, zindy commented on src/main/java/qupath/ext/align/gui/ImageAlignmentPane.java
> +			overlay.resetAffine();
Thank you for pointing this out Pete, 

> Is the null check not needed, i.e. is there absolutely no way for `getSelectedOverlay()` to return null?

I honestly don't know so I've restored the check on `overlay == null` you had in place previously (commit https://github.com/qupath/qupath-extension-align/pull/10/commits/a662e99d096c15cb59112d87333cef33b80b1146)

2025-04-12 08:14 UTC, zindy commented
@petebankhead 

> please let me know if you'd like to update your PRs, otherwise one of us will look into reviving this extension soon and can use them instead for inspiration.

I will update this particular PR because I would consider it a "bug" that needs fixing.

Regarding the other two PRs clogging the queue:
* https://github.com/qupath/qupath-extension-align/pull/8 is a "Nice to have" (IMHO) because it homogenises the way project entries are selected across QuPath
* https://github.com/qupath/qupath-extension-align/pull/7 is the one I'm the least happy with because it only answers part of the question "what do you want to apply the transform matrix to". My PR addresses "I want to transfer the contours from the fixed image to the overlay". But in the past we've also had "[combine the all the channels into a new project entry](https://forum.image.sc/t/qupath-scripting-4-image-combiner-register-images-and-create-project-entry/50484?page=2)" and I've been experimenting with "apply the transform matrix to the synchronised viewer that corresponds to the overlay" (a mouthful, I know), which potentially could be even more intuitive than the way [NDP.View does it with its two crosses](https://forum.image.sc/t/small-ui-issue-in-synchronized-multiview-with-rotated-image-s/73577/8).

So to answer your question: I wouldn't mind getting this "scaling bug" PR merged when you're happy with the code. Then definitely use the other two PRs for inspiration if they help you in any way.

Cheers,
Egor

2025-04-12 09:53 UTC, zindy commented on src/main/java/qupath/ext/align/gui/ImageServerOverlay.java
> +	private PixelCalibration viewerCalibration;
I went with `viewerImageCalibration` and `overlayImageCalibration`, is that OK?

2025-04-12 10:24 UTC, zindy commented on src/main/java/qupath/ext/align/gui/ImageServerOverlay.java
> +        // Calculate the a and y scaling factor
Right! I implemented a ~half ar...~ halfway solution in https://github.com/qupath/qupath-extension-align/pull/10/commits/d6e140068494361f3ae107a6fa6debebc942f2d1 which relies on `hasPixelSizeMicrons()` being true, so that none of `getPixelWidthMicrons()` and `getPixelHeightMicrons()` are NaN in my ratios.

I can totally check matching pixel units though if you prefer (like you asked).

2025-05-30 13:36 UTC, merged